"use server";

import { Resend } from 'resend';

// Make sure to pull the API key from environment variables
const resend = new Resend(process.env.RESEND_API_KEY);

export async function submitContactForm(formData: {
  name: string;
  email: string;
  phone: string;
  service: string;
  message: string;
}) {
  try {
    const { data, error } = await resend.emails.send({
      // Resend requires using this 'from' sandbox email until you verify your custom domain
      from: 'Hariniti Website <onboarding@resend.dev>', 
      to: 'harinitifinancesatish@gmail.com', 
      subject: `New Lead: ${formData.service || 'General Inquiry'}`,
      html: `
        <h2>New Client Inquiry from HariNitiFinance.com</h2>
        <table style="width: 100%; max-width: 600px; border-collapse: collapse; margin-top: 15px;">
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #ddd; width: 150px;"><strong>Name</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">${formData.name}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Email</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">${formData.email}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Phone Number</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">${formData.phone || 'N/A'}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Service</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">${formData.service || 'General'}</td>
          </tr>
        </table>
        
        <h3 style="margin-top: 25px;">Message Details:</h3>
        <div style="background-color: #f9f9f9; padding: 15px; border-radius: 5px; border-left: 4px solid #F1B24A;">
          ${formData.message.replace(/\n/g, '<br/>')}
        </div>
        
        <p style="margin-top: 30px; font-size: 12px; color: #666;">This message was automatically generated by your Resend API integration.</p>
      `
    });

    if (error) {
      console.error("Resend API Error:", error);
      return { success: false, error: error.message };
    }

    return { success: true };
  } catch (err: any) {
    console.error("Server Action Error:", err);
    return { success: false, error: err.message || 'Internal Server Error' };
  }
}
